import type { GetServerSideProps, InferGetServerSidePropsType, NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import {User} from '../types/user'
import styles from '../styles/Home.module.css'
import Selector from '../components/selector'
import TextInput from '../components/text-input'
import SubmitButton from '../components/submit-button'

const selectorAlgoData = {
  description: "Similarity",
  id: "Algorithm",
  values: [{name: "Euclidean", id: 1}, {name: "Pearson", id:2}]
}

export const getServerSideProps: GetServerSideProps = async({ params,res }) => {
  const result = await fetch("http://localhost:3000/api/users")
  const data: User[] = await result.json()

  return {
    props: {
      data
    }
  }
}


const Home: NextPage = ({ data }: InferGetServerSidePropsType<typeof getServerSideProps>) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div>
          <div className={styles.inputWrapper}>
            <Selector
                key="1"
                description={"User"}
                options={data}
            />
            <Selector
                key="2"
                description={selectorAlgoData.description}
                options={selectorAlgoData.values}
            />
            <TextInput
              text={"Results"}
            />
          </div>
          <div className={styles.buttonsWrapper}>
            <SubmitButton text="Find top matching users"/>
            <SubmitButton text="Find recommended movies"/>
            <SubmitButton text="Find recommendations, item-based"/>
          </div>
        </div>
      </main>
    </div>
  )
}

export default Home
