import type { GetServerSideProps, InferGetServerSidePropsType, NextPage } from 'next'
import Head from 'next/head'
import {User} from '../types/user'
import styles from '../styles/Home.module.css'
import InputForm from '../components/input-form'
import { useState } from 'react'
import { Match } from '../types/match'
import DataTable from '../components/data-table'

export const getServerSideProps: GetServerSideProps = async({ params,res }) => {
  const result = await fetch("http://localhost:3000/api/users")
  const users: User[] = await result.json()

  return {
    props: {
      users
    }
  }
}




const Home: NextPage = ({ users }: InferGetServerSidePropsType<typeof getServerSideProps>) => {
  const [resultData, setResultData] = useState<Match | null>(null);
  
  const handleDataRequest = async (userId: string, sim: string, numOfResults: string, apiPath: string) => {
    const requestString = `http://localhost:3000/api/recommendations/${apiPath}?userId=${userId}&simMethod=${sim}&numOfResults=${numOfResults}`

    console.log(requestString)
    const response = await fetch(requestString)
    const result = await response.json()

    if (response.status !== 400) {
      setResultData(result)
    }

    console.log(result)

  }


  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <InputForm
          users={users}
          formSubmit={(userId: string, sim: string, numOfResults: string, apiPath: string) => handleDataRequest(userId, sim, numOfResults, apiPath)}
        />
        {
          resultData !== null ? <DataTable tableData={resultData}/> : null
        }
      </main>
    </div>
  )
}

export default Home
