import type { GetServerSideProps, InferGetServerSidePropsType, NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import {User} from '../types/user'
import Options from '../components/options'
import styles from '../styles/Home.module.css'
import Selector from '../components/selector'

const selectorAlgoData = {
  description: "Similarity",
  id: "Algorithm",
  values: [{name: "Euclidean", id: 1}, {name: "Pearson", id:2}]
}

export const getServerSideProps: GetServerSideProps = async({
  params,
  res
}) => {
  const result = await fetch("http://localhost:3000/api/users")

  const data: User[] = await result.json()

  return {
    props: {
      data
    }
  }
}


const Home: NextPage = ({ data }: InferGetServerSidePropsType<typeof getServerSideProps>) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
      <div>
            <Selector
                key="1"
                description={"User"}
                options={data}
            />
            <Selector
                key="2"
                description={selectorAlgoData.description}
                options={selectorAlgoData.values}
            />
        </div>
      </main>
    </div>
  )
}

export default Home
